// Tableau de données produits

const produits = [
    {
    id: 101,
    categorie: "chaine-homme",
    fetes : "sain valentin",
    nom: "Aegis Steel ",
    lien: "produit.html?id=101",
    image: "assets/chaineshomme1.png",
    prix : "99.99€",
    description: "Avec son design épuré et moderne, Aegis Steel incarne la force tranquille. Fabriquée en acier inoxydable brossé, cette chaîne s’adresse à ceux qui aiment un style urbain, minimaliste mais affirmé.",
    conseils: "Parfaite sous une chemise légèrement ouverte ou associée à une montre métallique.<br>Parfaite sous une chemise légèrement ouverte ou associée à une montre métallique.<br>Idéale pour un look casual-chic ou streetwear.",
    entretien: "Nettoie-la avec un chiffon doux et un peu d’eau savonneuse.<br>Évite le contact avec le chlore ou les produits abrasifs.<br>Range-la à l’abri de l’humidité pour éviter les traces",
    },
    {
    id: 102, 
    categorie: "chaine-homme",   
    nom :"Onyx Flame",
    lien: "produit.html?id=102",
    image:"assets/chaineshomme2.png",
    prix : "49,99€",
    description: "Onyx Flame est une chaîne pour les esprits libres. Son cordon en cuir noir tressé associé à un fermoir en acier noir mat donne un look brut et viril.",
    conseils: "Superbe avec une veste en jean ou un blouson en cuir.<br>Peut être portée en accumulation avec d’autres bracelets pour un effet bohème ou rock.<br>Idéale pour les sorties ou festivals.",
    entretien: "Évite l’eau et le parfum sur le cuir.<br>Nourris le cuir avec une crème spécifique de temps en temps.<br>Range-la dans une pochette en tissu pour préserver la souplesse du cuir.",
    },
    {   
    id: 103,
    categorie: "chaine-homme",
    nom: "Nordic Drift",
    lien: "produit.html?id=103",
    image: "assets/chaineshommes3.png",
    prix : "777,77€" ,
    description: "Inspirée des légendes vikings, Nordic Drift est une chaîne argentée avec un pendentif en forme de rune ou de boussole. Elle symbolise l’aventure, la liberté et la force intérieure.",
    conseils: "Parfaite avec un pull à grosses mailles ou un sweat oversize.<br>À porter seule ou avec d’autres chaînes fines pour un effet superposé.<br>Donne du caractère à une tenue sobre.",
    entretien: "Utilise un chiffon doux pour polir l’argent.<br>En cas d’oxydation, trempe-la quelques minutes dans un mélange d’eau tiède, bicarbonate et jus de citron.",
    },
    { 
    id: 104, 
    categorie: "chaine-homme",  
    nom: "Noir Élément",
    lien: "produit.html?id=104",
    image: "assets/chaineshomme4.png",
    prix : "299,99€",
    description: "Discrète mais élégante, Noir Élément est une chaîne fine en titane noir, idéale pour les hommes qui aiment la sophistication sans trop en faire. Légère et résistante, elle se porte aussi bien au quotidien qu’en rendez-vous pro.",
    conseils: "Idéale avec un costume ou une chemise blanche.<br>Peut accompagner une montre fine noire ou argentée.<br>Se marie bien avec d'autres bijoux discrets comme une bague simple.",
    entretien: "Le titane est très résistant, mais un chiffon doux suffit pour lui redonner de l’éclat.<br>Évite de la plier ou de tirer dessus.<br>Range-la dans un écrin pour éviter les rayures.",
    
    },
     {
    id: 201,
    categorie: "pendentif-homme",
    nom: "Vortex Shield ",
    lien: "produit.html?id=201",
    image: "assets/pendentifshomme.png",
    prix : "39,99€",
    description: "Le Vortex Shield est un pendentif en forme de bouclier gravé, symbole de protection et de force. Sa finition acier vieilli lui donne un style brut et antique, parfait pour les esprits guerriers modernes.",
    conseils: "Idéal avec un col en V ou une chemise ouverte.<br>Se marie bien avec des vêtements en denim ou en cuir.<br>Ajoute une touche de caractère à un look sobre.",
    entretien: "Nettoie-le avec un chiffon microfibre sec ou légèrement humide.<br>Évite le contact avec l’eau salée ou chlorée.<br>Range-le à l’abri de la lumière directe pour préserver la patine.",
    },
    {
    id: 202,
    categorie: "pendentif-homme",
    nom :"Nuit Totem ",
    fetes : "sain valentin",
    lien: "produit.html?id=202",
    image:"assets/pendentifshomme2.png",
    prix : "19,99€",
    description: "Nuit Totem combine un disque d’onyx noir profond à une monture argentée ornée d’un œil stylisé. Ce pendentif est à la fois mystérieux et symbolique, parfait pour ceux qui aiment les bijoux chargés d’énergie.",
    conseils: "Parfait sur un col roulé ou un t-shirt uni foncé.<br>Peut être combiné avec d’autres bijoux en pierre (bracelets, bagues).<br>Idéal pour un style boho chic ou ésotérique.",
    entretien: "Nettoyer la pierre avec un chiffon doux sec, sans eau.<br>L’argent peut être poli avec un tissu spécial argent.<br>Garde-le dans une pochette pour éviter les rayures.",
    },
    {   
    id: 203,
    categorie: "pendentif-homme",
    nom: "Lupo Nero",
    lien: "produit.html?id=203",
    image: "assets/pendentifshomme3.png",
    prix : "499,99€",
    description: "Avec sa tête de loup finement sculptée en acier noir, Lupo Nero incarne l’instinct, la loyauté et la liberté. C’est un pendentif puissant, taillé pour ceux qui suivent leur propre voie.",
    conseils: "Idéal avec un look streetwear ou biker.<br>Va très bien avec des couleurs sombres ou un style militaire.<br>À porter seul, en pièce maîtresse.",
    entretien: "Lave-le à l’eau tiède savonneuse et sèche-le tout de suite.<br>Évite les produits abrasifs sur la finition noire.<br>Suspends-le quand tu ne le portes pas pour éviter les frottements.",
    },
    {    
    id: 204,
    categorie: "pendentif-homme",
    nom: "Nova Oris ",
    lien: "produit.html?id=204",
    image: "assets/pendentifshomme4.png",
    prix : "99,99€",
    description: "Nova Oris est un pendentif circulaire en acier poli miroir, gravé de symboles stellaires minimalistes. Inspiré de l’univers et du mystère de la nuit, il reflète la quête intérieure et l’élégance subtile.",
    conseils: "Parfait avec un look urbain épuré ou une tenue monochrome.<br>Idéal avec une veste oversize ou une chemise noire.<br>Convient pour des événements où le style discret est roi.",
    entretien: "Un chiffon doux suffit pour redonner de l’éclat à l’acier poli.<br>Évite les rayures en le rangeant dans un compartiment séparé.<br>N’utilise pas de produits chimiques sur la surface miroir.",
    
    },

    {
    id: 301,
    categorie: "bague-homme",
    nom: "Iron Pulse",
    fetes : "sain valentin",
    lien: "produit.html?id=301",
    image: "assets/bagueshommes1.png",
    prix : "499,99€",
    description: "Iron Pulse est une bague en acier inoxydable brossé, traversée par des lignes gravées qui rappellent les circuits industriels et la mécanique de précision. Moderne, robuste, et épurée.",
    conseils: "Parfaite pour un look techwear, urbain ou minimaliste.<br>À porter seule pour en souligner la puissance.<br>S’accorde bien avec une montre en métal ou un bracelet manchette.",
    entretien: "Nettoyer avec un chiffon doux et sec, ou un peu d’eau savonneuse.<br>Résistante, mais évite le contact prolongé avec l’eau salée.<br>Range-la à l’abri des autres bijoux pour éviter les rayures.",
    },
    {
    id: 302,
    categorie: "bague-homme",
    nom : "Obsidian Soul",
    lien: "produit.html?id=302",
    image:"assets/bagueshomme2.png" ,
    prix : "99,99€",
    description: "Obsidian Soul allie une monture en argent massif à une pierre d’onyx noir lisse, intense et profonde. Elle évoque l’introspection, le mystère et la force intérieure.",
    conseils: "Idéale avec un look noir ou monochrome.<br>Parfaite pour ceux qui aiment les pièces qui attirent l’œil sans en faire trop.<br>Peut se combiner avec des bijoux en pierre ou argent (pendentif, bracelet fin).",
    entretien: "Nettoyer l’onyx avec un chiffon doux, sans eau.<br>L’argent peut être poli avec un tissu spécial.<br>Évite les chocs sur la pierre.",
    },
    {   
    id: 303,
    categorie: "bague-homme",
    nom: "Serpentum",
    lien: "produit.html?id=304",
    image: "assets/bagueshommes3.png",
    prix : "799,99€",
    description: "Serpentum s’enroule autour du doigt comme une force ancienne. Son design serpenté en acier noir mat est un symbole de transformation, de protection et d’instinct.",
    conseils: "Parfaite pour un look rock, gothique ou alternatif.<br>À porter avec des vêtements sombres, en cuir ou denim.<br>S’accorde bien avec des pendentifs symboliques ou des piercings.",
    entretien: "Nettoyage à sec recommandé avec un chiffon doux.<br>Évite les produits abrasifs pour conserver la finition noire.<br>Ne pas exposer à l’humidité prolongée.",
    },
    {   
    id: 304, 
    categorie: "bague-homme",    
    nom: "Frost Sigil",
    lien: "produit.html?id=304",
    image: "assets/bagueshomme4.png",
    prix : "199,99€",
    description: "Inspirée des anneaux ancestraux nordiques, Frost Sigil est une bague plate et massive, ornée de symboles runiques gravés. Elle incarne la sagesse des anciens et la connexion à ses racines.",
    conseils: "Idéale avec une tenue sobre, chemise claire ou pull en maille.<br>Peut être portée en duo avec une chaîne nordique ou un bracelet en cuir.<br>Pour les amateurs de bijoux symboliques et intemporels.",
    entretien: "Nettoyer avec une lingette douce, eau tiède et savon neutre.<br>Polir si besoin avec un tissu spécial bijou.<br>Conserver dans une boîte ou un sac en tissu pour préserver la gravure.",
    
    },
    {
    id: 401,
    categorie: "montre-homme",
    nom: "Chrono Drift",
    lien: "produit.html?id=401",
    image: "assets/montreshomme1.png",
    prix : "299,99€",
    description: "Chrono Drift est une montre chronographe au boîtier acier brossé, bracelet cuir camel et cadran noir profond. Elle allie précision et élégance sportive, idéale pour les hommes actifs qui gardent le sens du détail.",
    conseils: "Parfaite avec une chemise blanche retroussée ou un blouson aviateur.<br>Associe-la avec des boots ou accessoires en cuir ton camel.<br>Idéale au quotidien comme en rendez-vous pro.",
    entretien: "Nettoie le boîtier avec un chiffon doux légèrement humide.<br>Évite l’eau pour préserver le cuir du bracelet.<br>Range-la dans un écrin pour éviter les chocs et la poussière.",
    },
    {
    id: 402,
    categorie: "montre-homme",
    nom : "Midnight Core",
    fetes : "sain valentin",
    lien: "produit.html?id=402",
    image:"assets/montreshomme2.png" ,
    prix : "599,99€",
    description: "Avec son look full black et son design minimaliste, Midnight Core est une montre urbaine, discrète et puissante. Boîtier mat, aiguilles fines, aucune fioriture : juste l’essentiel.",
    conseils: "S’associe à merveille avec un look monochrome ou techwear.<br>À porter avec une veste structurée ou un sweat oversize.<br>Idéale pour les looks de nuit ou de ville.",
    entretien: "Nettoyage avec un chiffon microfibre sec.<br>Évite les rayures sur le verre ou le boîtier en titane.<br>Conserve-la à l’abri de l’humidité pour garder son aspect mat.",
    },
    {  
    id: 403, 
    categorie: "montre-homme",
    nom: "Atlas Edge",
    lien: "produit.html?id=403",
    image: "assets/montreshomme3.png",
    prix : "99,99€",
    description: "Atlas Edge est conçue pour les esprits aventuriers. Résistante à l’eau, dotée d’un bracelet en nylon tissé kaki et d’un boîtier robuste, elle t’accompagne en rando comme en ville.",
    conseils: "Parfaite avec un look cargo, boots de rando ou veste coupe-vent.<br>Idéale pour les amateurs de nature, de trek ou de sports outdoor.<br>Fonctionne aussi bien avec un look militaire chic",
    entretien: "Lavage du bracelet à la main avec de l’eau tiède savonneuse.<br>Sécher complètement avant de ranger.<br>Vérifie régulièrement l’étanchéité si exposition à l’eau fréquente.",
    },
    { 
    id: 404, 
    categorie: "montre-homme",     
    nom: "Éclipse Royale",
    lien: "produit.html?id=404",
    image: "assets/montreshomm4.png",
    prix : "999,99€",
    description: "Éclipse Royale dévoile son mécanisme grâce à un cadran squelette raffiné, dans un boîtier acier poli et un bracelet en cuir noir lisse. C’est une montre élégante, raffinée et fascinante.",
    conseils: "Porte-la avec un costume, une chemise cintrée ou un trench.<br>Idéale pour les soirées, événements ou réunions importantes.<br>Associe-la à des boutons de manchette ou une bague discrète.",
    entretien: "Remonte-la manuellement si tu ne la portes pas tous les jours.<br>Nettoie le verre avec un chiffon doux et sec.<br>Garde-la dans une boîte spéciale montre automatique.",
    
    },
    {
    id: 501,
    categorie: "collier-femme",
    nom: "Luna Véla ",
    lien: "produit.html?id=501",
    image: "assets/collierfemme1.png",
    prix : "99,99€",
    description: "Luna Véla est un collier fin plaqué or, orné d’un délicat croissant de lune. À la fois poétique et discret, il incarne la féminité douce et rêveuse.",
    conseils: "Idéal avec un décolleté en V ou un top fluide.<br>Parfait en superposition avec d’autres colliers fins.<br>S’accorde bien avec des boucles d’oreilles dorées minimalistes.",
    entretien: "Évite le contact avec l’eau et le parfum.<br>Range-le à plat pour éviter les nœuds.<br>Range-le à plat pour éviter les nœuds.<br>Nettoie avec un chiffon doux et sec.",
    },
    {
    id: 502,
    categorie: "collier-femme",
    nom : "Éclat Rose",
    fetes : "sain valentin",
    lien: "produit.html?id=502",
    image:"assets/collierfemme2.png" ,
    prix : "49,99€",
    description: "Avec sa chaîne rose gold et sa pierre naturelle de quartz rose, Éclat Rose symbolise la douceur et l’amour. Il apporte une touche tendre à chaque tenue.",
    conseils: "Idéal pour un look romantique ou printanier.<br>Sublime avec une robe blanche, pastel ou un chemisier fleuri.<br>Se marie bien avec des bagues en pierres naturelles.",
    entretien: "Nettoie la pierre avec un chiffon sec (pas d’eau).<br>Conserve-le dans une pochette pour préserver la couleur du métal.<br>Évite l’exposition prolongée au soleil.",
    },
    {   
    id: 503, 
    categorie: "collier-femme",  
    nom: "Néon Élise",
    fetes : "sain valentin",
    lien: "produit.html?id=503",
    image: "assets/collierfemme3.png",
    prix : "777,77€",
    description: "Néon Élise est un collier ras-du-cou argenté décoré de strass géométriques. Brillant mais structuré, il incarne la femme moderne et audacieuse.",
    conseils: "Parfait avec un blazer, un col montant ou une robe noire.<br>Idéal en soirée ou pour un look de ville chic.<br>À porter seul pour le laisser capter la lumière.",
    entretien: "Nettoyer avec un chiffon microfibre sans produits chimiques.<br>Évite l’eau et l’humidité.<br>Range-le dans une boîte rigide.",
    },
    {   
    id: 504, 
    categorie: "collier-femme",   
    nom: "Sable Nacré",
    lien: "produit.html?id=504",
    image: "assets/collierfemme4.png" ,
    prix : "2999,99€",
    description: "Sable Nacré évoque les rivages et la douceur estivale. Son pendentif en forme de coquillage doré renferme une petite perle de nacre, symbole de féminité et d’élégance naturelle.",
    conseils: "Magnifique sur peau bronzée ou en été.<br>Porte-le avec une robe légère ou une tenue bohème.<br>Superbe avec des bracelets de cheville et sandales fines.",
    entretien: "Évite de le porter à la plage malgré son style marin.<br>Nettoie la nacre doucement sans frotter.<br>Range-le dans un petit sac en tissu doux.",
    
    },
    {
    id: 601,  
    categorie: "pendentif-femme",  
    nom: "Aura Mystica",
    lien: "produit.html?id=601",
    image: "assets/pendentifsfemme1.png",
    prix : "39,99€",
    description: "Aura Mystica est un pendentif en pierre d’améthyste naturelle, enchâssé dans une monture en argent ciselé aux motifs floraux. Il évoque la spiritualité, la sagesse intérieure et la sérénité.",
    conseils: "À porter avec un haut fluide, col rond ou décolleté subtil.<br>Sublime avec un style bohème ou ésotérique.<br>Peut être associé à d’autres bijoux en pierres naturelles.",
    entretien: "Nettoie l’améthyste avec un chiffon doux et sec.<br>L’argent peut être poli à l’aide d’un tissu spécial.<br>Évite les produits chimiques et la lumière directe prolongée.",
    },
    {
    id: 602, 
    categorie: "pendentif-femme",
    nom : "Feuille d’Orée",
    fetes : "sain valentin",
    lien: "produit.html?id=602",
    image:"assets/pendentifsfemme2.png" ,
    prix : "19,99€",
    description: "Feuille d’Orée est un pendentif en forme de feuille délicatement martelée, en métal doré à l’or fin. Il capture la lumière avec subtilité et célèbre la beauté de la nature.",
    conseils: "Idéal avec une robe longue, un col en V ou un top fluide.<br>Superbe en automne avec un gilet beige ou un pull oversize.<br>À porter seul ou avec des boucles d’oreilles assorties.",
    entretien: "Évite l’eau, les parfums et les frottements pour garder l’éclat.<br>Nettoyer avec un chiffon doux, sans pression.<br>Range-le dans une boîte rigide pour éviter les plis.",
    },
    {   
    id: 603, 
    categorie: "pendentif-femme",
    nom: "Perla Clara",
    lien: "produit.html?id=603",
    image: "assets/pendentifsfemme3.png",
    prix : "499,99€",
    description: "Perla Clara met en valeur une perle blanche nacrée suspendue à une fine chaîne en argent. Élégant et intemporel, c’est le pendentif idéal pour un look raffiné.",
    conseils: "Parfait pour des occasions spéciales ou tenues habillées.<br>Magnifique sur un col bateau ou une robe épurée.<br>    Peut être complété par un bracelet perlé ou une bague fine.",
    entretien: "Ne jamais frotter la perle : nettoie-la délicatement avec un chiffon doux<br>Évite toute exposition à l’eau, au parfum ou à l’alcool.<br>Range-la séparément pour préserver son éclat nacré.",
    },
    {   
    id: 604, 
    categorie: "pendentif-femme", 
    nom: "Lignes de Vie",
    lien: "produit.html?id=604",
    image: "assets/pendentifsfemme4.png" ,
    prix : "99,99€",
    description:"Lignes de Vie est un pendentif moderne en forme de cercle traversé par des motifs géométriques colorés en émail. Créatif, affirmé, il reflète la personnalité de celles qui osent l’originalité.",
    conseils: "Idéal avec un look coloré, arty ou urbain chic.<br>Sublime sur un t-shirt blanc, une veste structurée ou une robe unie.<br>Peut être associé à des boucles ou bagues graphiques.",
    entretien: "Nettoie délicatement avec un chiffon sec (pas d’eau sur l’émail).<br>Range-le à plat pour éviter les rayures.<br>Ne pas exposer à de fortes chaleurs ou à l’humidité.",
    
    },
    {
    id: 701, 
    categorie: "anneau-femme",    
    nom: "Étoile Fine",
    lien: "produit.html?id=701",
    image: "assets/anneauxfemme1.png",
    prix : "99,99€",
    description: "Étoile Fine est un anneau délicatement doré, orné d’un petit zircon clair qui brille comme une étoile au creux du doigt. Léger et lumineux, il évoque la grâce discrète.",
    conseils: "Parfait pour un look minimal chic ou romantique.<br>Se porte seul pour la finesse, ou empilé avec d’autres anneaux dorés.<br>Idéal en journée ou pour un dîner élégant.",
    entretien: "Nettoyer doucement avec un chiffon microfibre.<br>Éviter l’eau, le parfum et les frottements pour préserver la brillance.<br>Ranger à l’abri de l’humidité dans une petite boîte.",
    },
    {
    id: 702, 
    categorie: "anneau-femme",
    nom : "Terra Lune",
    fetes : "sain valentin",
    lien: "produit.html?id=702",
    image:"assets/anneauxfemme2.png"  ,
    prix : "49,99€",
    description: "Terra Lune allie la force de l’argent à la douceur d’une aventurine verte. Inspirée par la nature et les énergies terrestres, cette bague invite à la sérénité.",
    conseils: "Parfaite avec un style bohème, naturel ou vintage.<br>À porter avec des tons verts, beiges ou des vêtements en lin.<br>Se marie bien avec d'autres bijoux en pierres.",
    entretien: "Nettoie la pierre avec un chiffon doux, sans eau.<br>L’argent peut être poli avec un tissu spécial.<br>Évite les chocs ou le contact prolongé avec des produits chimiques.",
    },
    {  
    id: 703, 
    categorie: "anneau-femme", 
    nom: "Flamme Libre ",
    lien: "produit.html?id=703",
    image: "assets/anneauxfemme3.png",
    prix: "777,77€",
    description: "Flamme Libre est une bague dorée au design ajouré, formant des vagues ou flammes abstraites. Elle célèbre les esprits libres, puissants et créatifs.",
    conseils: "Superbe avec une tenue audacieuse, colorée ou artistique.<br>À porter en statement piece ou en mix avec des bijoux graphiques.<br>Idéale pour les créatives et les non-conformistes.",
    entretien: "Nettoyage à sec avec un chiffon doux.<br>Le laiton peut foncer légèrement : utilise un chiffon spécial laiton si besoin.<br>Évite l’eau et les frottements pour garder son éclat.",
    },
    {   
    id: 704,   
    categorie: "anneau-femme",  
    nom: "Ligne Claire",
    lien: "produit.html?id=704",
    image: "assets/anneauxfemme4.png",
    prix : "2999,99€",
    description: "Ligne Claire est un anneau argenté au fini miroir, simple mais ultra élégant. Son design lisse et pur en fait une pièce intemporelle et moderne à la fois.",
    conseils: "Parfait pour un look épuré, urbain ou professionnel.<br>S’accorde bien avec des bagues géométriques ou des bijoux en acier.<br>Idéal pour une tenue noire, blanche ou monochrome.",
    entretien: "Nettoyage facile avec un chiffon doux légèrement humide.<br>Résiste bien à l’usure quotidienne, mais évite les rayures.<br>À ranger dans une pochette pour éviter les contacts avec d'autres bijoux.",
    
    },
    {
    id: 801, 
    categorie: "boucle-femme",
    nom: "Comète Douce",
    fetes : "sain valentin",
    lien: "produit.html?id=801",
    image: "assets/bouclesoreillesfemme1.png",
    prix : "299,99€",
    description: "Comète Douce est une paire de puces d’oreilles délicates, dorées à l’or fin et serties d’un strass lumineux façon étoile. Elles apportent une touche d’éclat sans jamais en faire trop.",
    conseils: "Idéales pour le quotidien ou les occasions discrètes.<br>Parfaites avec une coiffure relevée, un maquillage doux ou un chemisier clair.<br>S’accordent bien avec un collier fin doré.",
    entretien: "Nettoyer doucement avec un chiffon sec.<br>Éviter parfum, eau et cosmétiques.<br>Conserver dans une boîte pour éviter les rayures.",
    },
    {
    id: 802, 
    categorie: "boucle-femme",
    nom : "Solea Bohème",
    lien: "produit.html?id=802",
    image:"assets/bouclesoreillesfemme2.png"  ,
    prix : "599,99€",
    description: "Solea Bohème sont des créoles fines agrémentées de petites pampilles en coquillage et perles naturelles. Elles évoquent l’été, la liberté et les paysages ensoleillés.",
    conseils: "Superbes avec une robe longue, un top fluide ou un look bohème.<br>À porter avec les cheveux lâchés ou tressés.<br>S’associent bien avec des bracelets de cheville ou des bagues en nacre.",
    entretien: "Évite l’eau salée, le sable ou l’humidité.<br>Nettoie les pampilles avec un chiffon doux, sans frotter.<br>Range-les dans une pochette souple pour préserver leur forme.",
    },
    {   
    id: 803, 
    categorie: "boucle-femme",
    nom: "Nocturne Élégance",
    lien: "produit.html?id=803",
    image: "assets/bouclesoreillesfemme3.png" ,
    prix : "99,99€",
    description: "Nocturne Élégance est une paire de boucles d’oreilles pendantes en acier argenté, au design graphique moderne. Élancées et raffinées, elles structurent le visage avec assurance.",
    conseils: "Parfaites avec un look de soirée ou un tailleur noir.<br>Sublimes sur cheveux attachés, col roulé ou top asymétrique.<br>Idéales avec une bague statement ou un maquillage intense.",
    entretien: "Résistent bien à l’usure, mais à nettoyer à sec.<br>Éviter les contacts avec d'autres métaux pour garder leur brillance.<br>Ranger à l’abri des frottements.",
    },
    {    
    id: 804, 
    categorie: "boucle-femme",
    nom: "Rosée Antique",
    lien: "produit.html?id=804",
    image: "assets/bouclesoreillesfemme4.png" ,
    prix : "999,99€",
    description: "Rosée Antique est une paire de dormeuses inspirées des bijoux anciens, avec une monture dorée finement travaillée et une pierre rose vintage en leur centre. Un charme intemporel.",
    conseils: "Idéales pour un look romantique ou rétro.<br>Superbes avec une robe fluide, un chemisier dentelle ou une coiffure à l’ancienne.<br>À associer avec des bijoux en pierre ou des colliers vintage.",
    entretien: "Nettoie délicatement avec un chiffon doux et sec.<br>Évite l’eau, les parfums et les chocs.<br>Conserve-les dans une boîte doublée de tissu.",
    
    },
    {    
    id: 901, 
    categorie: "collier",
    nom: "Lune Éclatante",
    lien: "produit.html?id=901",
    image: "assets/bouclesoreillesfemme4.png" ,
    prix : "999,99€",
    description: "Lune Éclatante est une chaîne dorée légère, ornée d’un pendentif en forme de lune martelée à la main. Elle joue avec la lumière et évoque la féminité céleste.",
    conseils: "Idéale avec un décolleté en V ou une robe fluide.<br>Se porte très bien en superposition avec d'autres colliers fins.<br>Parfaite pour les looks doux, poétiques ou mystiques.",
    entretien: "Évite le contact avec l’eau et les produits chimiques.<br>Range-la dans une pochette pour éviter les frottements.<br>Nettoie avec un chiffon doux sec.",
        
    },
    {    
    id: 902, 
    categorie: "collier",
    nom: "Écorce Dorée",
    lien: "produit.html?id=902",
    image: "assets/bouclesoreillesfemme4.png" ,
    prix : "999,99€",
    description: "Écorce Dorée mêle la robustesse d’une chaîne torsadée effet bronze à la douceur d’une perle d’eau douce en pendentif. Une harmonie entre force et délicatesse.",
    conseils: "Sublime avec un chemisier blanc, beige ou crème.<br>Idéale pour un look nature chic ou bohème.<br>Se marie bien avec des boucles en perles ou des bijoux en bois.",
    entretien: "Nettoyer la perle sans frotter.<br>Éviter l’eau salée ou le parfum.<br>Conserver à plat pour éviter que la chaîne ne s’emmêle.",
            
    },
    {    
    id: 903, 
    categorie: "collier",
    nom: "Flamme Haute",
    lien: "produit.html?id=903",
    image: "assets/bouclesoreillesfemme4.png" ,
    prix : "999,99€",
    description: "Flamme Haute est une chaîne ras-du-cou audacieuse composée de maillons dorés plats et larges. Un bijou statement à l’énergie vibrante et affirmée.",
    conseils: "À porter avec un haut noir, un blazer ou une tenue de soirée.<br>Se suffit à elle seule pour un effet stylé instantané.<br>Peut être assortie à des créoles dorées ou une manchette.",
    entretien: "Nettoyer avec un chiffon sec après chaque utilisation.<br>Éviter les produits cosmétiques.<br>Ranger dans une boîte rigide.",
    },
    {    
    id: 904, 
    categorie: "collier",
    nom: "Clarté d’Azur",
    lien: "produit.html?id=904",
    image: "assets/bouclesoreillesfemme4.png" ,
    prix : "999,99€",
    description: "Clarté d’Azur est une chaîne fine en argent ornée d’un pendentif en forme de goutte bleue translucide (verre ou topaze). Elle évoque la fraîcheur et la simplicité raffinée.",
    conseils: "Idéale pour une tenue estivale, un top clair ou une robe fluide.<br>À porter avec des bijoux argentés ou bleutés.<br>Met en valeur les teints clairs ou bronzés.",
    entretien: "L’argent peut être nettoyé avec un tissu spécial.<br>Protéger le pendentif des chocs.<br>Conserver à l’abri de l’humidité et de la lumière directe.",
                    
},
]


